# Generated by Django 2.1.7 on 2019-04-08 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=50, verbose_name='患者ID')),
                ('patientName', models.CharField(max_length=50, verbose_name='患者姓名')),
                ('patientBirthDate', models.CharField(max_length=100, verbose_name='患者出生日期')),
                ('patientBirthTime', models.CharField(max_length=100, verbose_name='患者出生时间')),
                ('patientSex', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10)),
                ('patientWeight', models.CharField(max_length=100, verbose_name='患者体重')),
                ('patientStatus', models.CharField(choices=[('male', '未怀孕'), ('female', '已怀孕')], default='female', max_length=10)),
                ('studyID', models.CharField(max_length=50, verbose_name='检查ID')),
                ('accessionNumber', models.CharField(max_length=50, verbose_name='检查号')),
                ('studyInstanceUID', models.CharField(max_length=500, verbose_name='检查实例号')),
                ('studyDate', models.CharField(max_length=50, verbose_name='检查日期')),
                ('studyTime', models.CharField(max_length=50, verbose_name='检查时间')),
                ('modalitiesinStudy', models.CharField(max_length=50, verbose_name='检查类型')),
                ('bodyPartExamined', models.CharField(max_length=50, verbose_name='检查的部位')),
                ('studyDescription', models.CharField(max_length=300, verbose_name='检查的描述')),
                ('patientAge', models.CharField(max_length=300, verbose_name='真实年龄')),
                ('seriesNumber', models.CharField(max_length=50, verbose_name='序列号')),
                ('seriesInstanceUID', models.CharField(max_length=500, verbose_name='序列实例号')),
                ('modality', models.CharField(max_length=200, verbose_name='检查模态')),
                ('seriesDescription', models.CharField(max_length=300, verbose_name='检查描述')),
                ('seriesDate', models.CharField(max_length=50, verbose_name='检查日期')),
                ('seriesTime', models.CharField(max_length=50, verbose_name='检查时间')),
                ('sOPInstanceUID', models.CharField(max_length=500, verbose_name='SOP实例UID')),
                ('instanceNumber', models.CharField(max_length=50, verbose_name='图像码')),
                ('columns', models.CharField(max_length=50, verbose_name='列')),
                ('rows', models.CharField(max_length=50, verbose_name='行')),
                ('acquisitionNumber', models.CharField(max_length=50, verbose_name='获取码')),
                ('photometricInterpretation', models.CharField(max_length=50, verbose_name='图片矩阵解释')),
                ('bitsAllocated', models.CharField(max_length=50, verbose_name='bitsAllocated')),
                ('bitsStored', models.CharField(max_length=50, verbose_name='BitsStored')),
                ('pixelRepresentation', models.CharField(max_length=50, verbose_name='PixelRepresentation')),
                ('samplesPerPixel', models.CharField(max_length=50, verbose_name='SamplesPerPixel')),
                ('pixelSpacing', models.CharField(max_length=50, verbose_name='PixelSpacing')),
                ('highBit', models.CharField(max_length=50, verbose_name='HighBit')),
                ('rescaleSlope', models.CharField(max_length=50, verbose_name='RescaleSlope')),
                ('rescaleIntercept', models.CharField(max_length=50, verbose_name='RescaleIntercept')),
                ('imageOrientation', models.CharField(max_length=500, verbose_name='ImageOrientation')),
                ('imagePosition', models.CharField(max_length=500, verbose_name='ImagePosition')),
                ('frameOfReferenceUID', models.CharField(max_length=500, verbose_name='FrameOfReferenceUID')),
                ('imageType', models.CharField(max_length=500, verbose_name='ImageType')),
                ('username', models.CharField(max_length=50, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': 'DICOM信息',
                'verbose_name_plural': 'DICOM信息',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名')),
                ('desc', models.CharField(max_length=300, verbose_name='图片描述')),
                ('image_real', models.ImageField(upload_to='picture/%Y/%m', verbose_name='具体图片')),
                ('url', models.CharField(default='', max_length=200, verbose_name='访问地址')),
                ('visitors', models.IntegerField(default=0, verbose_name='浏览人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image_mark', models.ImageField(upload_to='picture/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
