# Generated by Django 2.1.7 on 2019-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20190410_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimageinfo',
            name='baseName',
            field=models.CharField(default='', max_length=200, verbose_name='图片名称'),
        ),
    ]
