# Generated by Django 2.1.7 on 2019-04-17 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_medicalimageinfo_basename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(default='', max_length=50, verbose_name='医生姓名')),
                ('suggest', models.CharField(default='', max_length=500, verbose_name='医生建议')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('dicomInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.DICOMInformation', verbose_name='医学影像信息')),
            ],
            options={
                'verbose_name': '医生建议',
                'verbose_name_plural': '医生建议',
            },
        ),
    ]
