# Generated by Django 2.1.7 on 2019-04-20 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_doctorsuggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSuggestForThyroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(default='', max_length=50, verbose_name='医生姓名')),
                ('suggest', models.CharField(default='', max_length=500, verbose_name='医生建议')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('medicalImageInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.MedicalImageInfo', verbose_name='医学处理结果信息')),
            ],
            options={
                'verbose_name': '甲状腺良恶性医生建议',
                'verbose_name_plural': '甲状腺良恶性医生建议',
            },
        ),
        migrations.AlterModelOptions(
            name='doctorsuggest',
            options={'verbose_name': 'dicom医生建议', 'verbose_name_plural': 'dicom医生建议'},
        ),
        migrations.AlterField(
            model_name='dicominformation',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Picture', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='doctorsuggest',
            name='dicomInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.DICOMInformation', verbose_name='DICOM信息'),
        ),
    ]
