# Generated by Django 2.1.7 on 2019-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20190420_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='username',
            field=models.CharField(default='15735657418@163.com', max_length=50, verbose_name='上传用户'),
        ),
    ]
