# Generated by Django 2.1.7 on 2019-04-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_picture_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='suggest',
            field=models.CharField(default=' ', max_length=500, verbose_name='医生建议'),
        ),
    ]
